name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Lint SVG files
        run: |
          sudo apt-get -y install scour
          make lint-svg

      - name: Lint shell scripts
        run: |
          sudo apt-get -y install shellcheck
          make lint-shell
