name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          python get-poetry.py -y
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint SVG files
        run: |
          sudo apt-get -y install scour
          make lint-svg

      - name: Lint shell scripts
        run: |
          sudo apt-get -y install shellcheck
          make lint-shell

      - name: Lint Python files
        run: poetry run make lint-python
