name: rsvg-convert

on: [push]

jobs:
  rsvg-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Convert SVG to PNG using rsvg-convert
        run: |
          sudo apt-get -y install librsvg2-bin
          make rsvg-convert
